# Initialization

In [49]:
import os
from pathlib import Path
from dotenv import load_dotenv
from sqlalchemy import create_engine
import pandas as pd
import joblib
import optuna
import json

In [17]:
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, confusion_matrix

In [5]:
current_dir = os.getcwd()
current_dir

'e:\\University\\OOP\\FinanceTracking'

In [6]:
if current_dir.split("\\")[-1] != 'notebooks':
    target_path = os.path.join('src', 'ml-service', 'notebooks')
    os.chdir(target_path)

In [7]:
load_dotenv()

True

In [51]:
DB_URL = f"postgresql+psycopg2://{os.getenv('DB_USER')}:{os.getenv('DB_PASS')}@{os.getenv('DB_HOST')}/{os.getenv('DB_NAME')}"

TEST_SIZE = 0.2 # 20%
RANDOM_STATE = 0

EXPORT_PATH = "../app/models/exports"
MODEL_EXPORT_PATH = EXPORT_PATH + "/model.joblib"
CATEGORIES_EXPORT_PATH = EXPORT_PATH + "/categories.json"

# Data loading

Here you can configure your own data loading pipeline. We'll use our own because our data is stored inside PostgreSQL DB.

This whole notebook training flow will work with any DataFrame that has columns `name` and `category`.

In [9]:
engine = create_engine(DB_URL)

In [10]:
df = pd.read_sql("SELECT * FROM products", engine)

In [11]:
df.head()

,id,name,category,preprocessed,created_at
0,202,"Нектар вишневий Наш Сік 1,93л",Напої,nektar vyshnevyj nash sik,2025-07-12 16:38:21.971804
1,6730,Цукерки Amos 4D Pineapple Burst у формі ананас...,Солодощі,tsukerky amos pineapple burst formi ananasa,2025-07-12 16:38:21.971804
2,6732,Набір подарунковий чашка 380мл з шоколадною ку...,Солодощі,nabir podarunkovyj chashka shokoladnoju kul'koju,2025-07-12 16:38:21.971804
3,6733,Цукерки Toffifee білий шоколад 125г,Солодощі,tsukerky toffifee bilyj shokolad,2025-07-12 16:38:21.971804
4,6734,Соломка Sergini Столична солодка 40г,Солодощі,solomka sergini stolychna solodka,2025-07-12 16:38:21.971804

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 127853 entries, 0 to 127852
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            127853 non-null  int64
 1   name          127853 non-null  object
 2   category      127853 non-null  object
 3   preprocessed  127853 non-null  object
 4   created_at    127853 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 4.9+ MB

In [13]:
df = df[["name", "category"]]
df.head()

                                                name  category
0                      Нектар вишневий Наш Сік 1,93л     Напої
1  Цукерки Amos 4D Pineapple Burst у формі ананас...  Солодощі
2  Набір подарунковий чашка 380мл з шоколадною ку...  Солодощі
3                Цукерки Toffifee білий шоколад 125г  Солодощі
4               Соломка Sergini Столична солодка 40г  Солодощі

In [24]:
df.groupby("category")[["name"]].count().sort_values(by="name", ascending=False)

                           name
category
Алкоголь                  13558
Товари для дому           11376
Солодощі                  10479
Гігієна та догляд         10085
Одяг та взуття             6677
Товари для дітей           6553
Напої                      6462
Молочні продукти           5878
М'ясо та ковбасні вироби   5770
Фрукти та овочі            4747
Бакалія                    4719
Товари для кухні           4116
Кулінарія                  4061
Пекарня                    4059
Соуси та спеції            3376
Садівництво                3356
Книги                      2875
Риба та морепродукти       2720
Побутова хімія             2717
Консерви                   2497
Товари для тварин          2441
Канцелярія                 2354
Чипси та снеки             1908
Тютюнові вироби            1810
Хобі та відпочинок         1723
Напівфабрикати              771
Електроніка                 569
Яйця                        114
Жуйки                        51
Лід                          26
Сертифікати                   5

As we can see, dataset is very imbalanced. We'll leave only the most interesting categories and group some similar categories together.

In [27]:
categories_to_group = {
    "Побутова хімія": "Гігієна та догляд",
    "Пекарня": "Кулінарія",
    "Чипси та снеки": "Кулінарія",
    "Консерви": "Кулінарія",
    "Напівфабрикати": "Кулінарія",
    "Риба та морепродукти" : "М'ясо та ковбасні вироби",
    "Жуйки" : "Солодощі"
}

df['category'] = df['category'].replace(categories_to_group)

In [28]:
categories_to_rename = {
    "Кулінарія": "Готова їжа, снеки та напівфабрикати",
    "М'ясо та ковбасні вироби": "М'ясо та риба"
}

df['category'] = df['category'].replace(categories_to_rename)

In [31]:
categories_to_leave = [
    "Алкоголь",
    "Солодощі",
    "Гігієна та догляд",
    "Одяг та взуття",
    "Напої",
    "Молочні продукти",
    "М'ясо та риба",
    "Фрукти та овочі",
    "Бакалія",
    "Готова їжа, снеки та напівфабрикати",
    "Соуси та спеції",
    "Книги",
    "Канцелярія",
    "Тютюнові вироби",
    "Електроніка",
]

df = df[df['category'].isin(categories_to_leave)].copy()

# Preprocessing

In [32]:
import re
import string
import transliterate

punctuation_to_space = string.punctuation.replace("'", "")
space_translation = str.maketrans(dict.fromkeys(punctuation_to_space, " "))
delete_translation = str.maketrans(dict.fromkeys("’«»", ""))

def normalize_ukrainian_text(text: str) -> str:
    """Processes ukrainian text string into a text string that is ready to be used inside a prediction model."""
    text = text.translate(space_translation).translate(delete_translation)
    
    res = transliterate.translit(text, language_code='uk', reversed=True)
    
    # Add spaces before capital letters (for camelCase words)
    res = re.sub(r'(?<=[a-z])(?=[A-Z])', ' ', res).lower()

    words = res.split()
    processed_words = []
    
    for word in words:
        if len(word) < 2:
            continue
            
        if any(char.isdigit() for char in word):
            continue
            
        if not re.fullmatch(r"[a-zA-Z'-]{3,40}", word):
            continue
            
        processed_words.append(word)
    
    return ' '.join(processed_words)

In [33]:
df["preprocessed"] = df["name"].apply(normalize_ukrainian_text)
df.head()

,name,category,preprocessed
0,"Нектар вишневий Наш Сік 1,93л",Напої,nektar vyshnevyj nash sik
1,Цукерки Amos 4D Pineapple Burst у формі ананас...,Солодощі,tsukerky amos pineapple burst formi ananasa
2,Набір подарунковий чашка 380мл з шоколадною ку...,Солодощі,nabir podarunkovyj chashka shokoladnoju kul'koju
3,Цукерки Toffifee білий шоколад 125г,Солодощі,tsukerky toffifee bilyj shokolad
4,Соломка Sergini Столична солодка 40г,Солодощі,solomka sergini stolychna solodka

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 98143 entries, 0 to 127754
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          98143 non-null  object
 1   category      98143 non-null  object
 2   preprocessed  98143 non-null  object
dtypes: object(3)
memory usage: 3.0+ MB

In [37]:
df.groupby("category")[["name"]].count().sort_values(by="name", ascending=False)

                                      name
category
Алкоголь                             13558
Готова їжа, снеки та напівфабрикати  13296
Гігієна та догляд                    12802
Солодощі                             10530
М'ясо та риба                         8490
Одяг та взуття                        6677
Напої                                 6462
Молочні продукти                      5878
Фрукти та овочі                       4747
Бакалія                               4719
Соуси та спеції                       3376
Книги                                 2875
Канцелярія                            2354
Тютюнові вироби                       1810
Електроніка                            569

# Train/test split

In [35]:
X_train_full, X_test, y_train_full, y_test = train_test_split(
    df['preprocessed'], 
    df['category'], 
    test_size=TEST_SIZE, 
    random_state=RANDOM_STATE, 
    stratify=df['category']
)

# Model training

## Hyperparameter tuning

In [ ]:
def objective(trial: optuna.Trial):
    ngram_max = trial.suggest_int("ngram_max", 2, 5)
    alpha = trial.suggest_float("alpha", 1e-10, 1.0, log=True)
    
    pipeline = Pipeline([
        ('tfidf', TfidfVectorizer(analyzer='char_wb', ngram_range=(1, ngram_max))),
        ('classifier', MultinomialNB(alpha=alpha))
    ])
    
    skf = StratifiedKFold(n_splits=3, shuffle=True, random_state=RANDOM_STATE)
    
    # Using f1_macro because dataset is very imbalanced
    score = cross_val_score(
        pipeline, X_train_full, y_train_full, 
        cv=skf, n_jobs=-1, scoring='f1_macro'
    )
    return score.mean()

In [39]:
study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=30, show_progress_bar=True)

[I 2026-03-08 16:30:22,916] A new study created in memory with name: no-name-a3b99bd1-0078-43e8-95ef-91def890f876

  0%|          | 0/30 [00:00<?, ?it/s]

[I 2026-03-08 16:30:30,274] Trial 0 finished with value: 0.6519057374932342 and parameters: {'ngram_max': 2, 'alpha': 0.16929208554844727}. Best is trial 0 with value: 0.6519057374932342.
[I 2026-03-08 16:30:42,804] Trial 1 finished with value: 0.9252642837625905 and parameters: {'ngram_max': 5, 'alpha': 0.01839603650780102}. Best is trial 1 with value: 0.9252642837625905.
[I 2026-03-08 16:30:49,365] Trial 2 finished with value: 0.6558123007622629 and parameters: {'ngram_max': 2, 'alpha': 9.841772188564112e-09}. Best is trial 1 with value: 0.9252642837625905.
[I 2026-03-08 16:30:56,676] Trial 3 finished with value: 0.6558123007622629 and parameters: {'ngram_max': 2, 'alpha': 1.0075492673763716e-09}. Best is trial 1 with value: 0.9252642837625905.
[I 2026-03-08 16:31:04,336] Trial 4 finished with value: 0.8709483658239231 and parameters: {'ngram_max': 3, 'alpha': 5.93583170167752e-08}. Best is trial 1 with value: 0.9252642837625905.
[I 2026-03-08 16:31:15,616] Trial 5 finished with value: 0.9269848751948114 and parameters: {'ngram_max': 5, 'alpha': 0.00040160555145203603}. Best is trial 5 with value: 0.9269848751948114.
[I 2026-03-08 16:31:21,423] Trial 6 finished with value: 0.8744310476893421 and parameters: {'ngram_max': 3, 'alpha': 7.895284574143007e-07}. Best is trial 5 with value: 0.9269848751948114.
[I 2026-03-08 16:31:26,857] Trial 7 finished with value: 0.8779294296920469 and parameters: {'ngram_max': 3, 'alpha': 0.07902176129600774}. Best is trial 5 with value: 0.9269848751948114.
[I 2026-03-08 16:31:35,912] Trial 8 finished with value: 0.9181220286750791 and parameters: {'ngram_max': 5, 'alpha': 2.866230054680483e-09}. Best is trial 5 with value: 0.9269848751948114.
[I 2026-03-08 16:31:43,159] Trial 9 finished with value: 0.9157155826127045 and parameters: {'ngram_max': 4, 'alpha': 8.787081078135622e-06}. Best is trial 5 with value: 0.9269848751948114.
[I 2026-03-08 16:31:50,449] Trial 10 finished with value: 0.9192458222010095 and parameters: {'ngram_max': 4, 'alpha': 0.0008217275997372314}. Best is trial 5 with value: 0.9269848751948114.
[I 2026-03-08 16:31:59,570] Trial 11 finished with value: 0.9271791119950491 and parameters: {'ngram_max': 5, 'alpha': 0.001217344949717882}. Best is trial 11 with value: 0.9271791119950491.
[I 2026-03-08 16:32:10,026] Trial 12 finished with value: 0.927109758143447 and parameters: {'ngram_max': 5, 'alpha': 0.001091547473778827}. Best is trial 11 with value: 0.9271791119950491.
[I 2026-03-08 16:32:17,606] Trial 13 finished with value: 0.9184173120870796 and parameters: {'ngram_max': 4, 'alpha': 0.00024648901814202853}. Best is trial 11 with value: 0.9271791119950491.
[I 2026-03-08 16:32:29,700] Trial 14 finished with value: 0.9267938385195428 and parameters: {'ngram_max': 5, 'alpha': 0.004258491631132274}. Best is trial 11 with value: 0.9271791119950491.
[I 2026-03-08 16:32:38,674] Trial 15 finished with value: 0.916692341375894 and parameters: {'ngram_max': 4, 'alpha': 3.109155227811942e-05}. Best is trial 11 with value: 0.9271791119950491.
[I 2026-03-08 16:32:49,785] Trial 16 finished with value: 0.8544764626192785 and parameters: {'ngram_max': 5, 'alpha': 0.4864041852579818}. Best is trial 11 with value: 0.9271791119950491.
[I 2026-03-08 16:33:00,481] Trial 17 finished with value: 0.9240171780397951 and parameters: {'ngram_max': 5, 'alpha': 1.228421363271665e-05}. Best is trial 11 with value: 0.9271791119950491.
[I 2026-03-08 16:33:09,266] Trial 18 finished with value: 0.9196517997538626 and parameters: {'ngram_max': 4, 'alpha': 0.005037294785205791}. Best is trial 11 with value: 0.9271791119950491.
[I 2026-03-08 16:33:20,521] Trial 19 finished with value: 0.926477984969285 and parameters: {'ngram_max': 5, 'alpha': 0.00011882824594707679}. Best is trial 11 with value: 0.9271791119950491.
[I 2026-03-08 16:33:29,801] Trial 20 finished with value: 0.9137777431543173 and parameters: {'ngram_max': 4, 'alpha': 1.0693985225655118e-06}. Best is trial 11 with value: 0.9271791119950491.
[I 2026-03-08 16:33:39,679] Trial 21 finished with value: 0.9270423405866843 and parameters: {'ngram_max': 5, 'alpha': 0.001501691165708011}. Best is trial 11 with value: 0.9271791119950491.
[I 2026-03-08 16:33:49,659] Trial 22 finished with value: 0.926718289116538 and parameters: {'ngram_max': 5, 'alpha': 0.003814110795504282}. Best is trial 11 with value: 0.9271791119950491.
[I 2026-03-08 16:33:59,599] Trial 23 finished with value: 0.9235346408780742 and parameters: {'ngram_max': 5, 'alpha': 0.03827255794329474}. Best is trial 11 with value: 0.9271791119950491.
[I 2026-03-08 16:34:08,968] Trial 24 finished with value: 0.9269623995127398 and parameters: {'ngram_max': 5, 'alpha': 0.0019549488654891658}. Best is trial 11 with value: 0.9271791119950491.
[I 2026-03-08 16:34:16,903] Trial 25 finished with value: 0.9059337864768202 and parameters: {'ngram_max': 4, 'alpha': 1.0663283658027536e-10}. Best is trial 11 with value: 0.9271791119950491.
[I 2026-03-08 16:34:27,791] Trial 26 finished with value: 0.9258716760570399 and parameters: {'ngram_max': 5, 'alpha': 6.662726571732446e-05}. Best is trial 11 with value: 0.9271791119950491.
[I 2026-03-08 16:34:36,515] Trial 27 finished with value: 0.9183594023330931 and parameters: {'ngram_max': 4, 'alpha': 0.016132172096263078}. Best is trial 11 with value: 0.9271791119950491.
[I 2026-03-08 16:34:47,615] Trial 28 finished with value: 0.7689667244159715 and parameters: {'ngram_max': 5, 'alpha': 0.9287909511834503}. Best is trial 11 with value: 0.9271791119950491.
[I 2026-03-08 16:34:53,447] Trial 29 finished with value: 0.876084511018938 and parameters: {'ngram_max': 3, 'alpha': 3.3944831882003757e-06}. Best is trial 11 with value: 0.9271791119950491.

## Final model evaluation

In [41]:
best_params = study.best_params
eval_pipeline = Pipeline([
    ('tfidf', TfidfVectorizer(
        analyzer='char_wb', 
        ngram_range=(1, best_params['ngram_max'])
    )),
    ('classifier', MultinomialNB(alpha=best_params['alpha']))
])

In [42]:
eval_pipeline.fit(X_train_full, y_train_full)

Pipeline(steps=[('tfidf',
                 TfidfVectorizer(analyzer='char_wb', ngram_range=(1, 5))),
                ('classifier', MultinomialNB(alpha=0.001217344949717882))])

In [43]:
y_pred = eval_pipeline.predict(X_test)
print(classification_report(y_test, y_pred))

                                     precision    recall  f1-score   support

                           Алкоголь       0.99      0.98      0.98      2712
                            Бакалія       0.88      0.89      0.89       944
Готова їжа, снеки та напівфабрикати       0.91      0.81      0.86      2659
                  Гігієна та догляд       0.99      0.99      0.99      2561
                        Електроніка       0.99      0.97      0.98       114
                         Канцелярія       0.93      0.85      0.89       471
                              Книги       0.87      0.98      0.92       575
                      М'ясо та риба       0.93      0.96      0.95      1698
                   Молочні продукти       0.96      0.95      0.96      1176
                              Напої       0.93      0.97      0.95      1292
                     Одяг та взуття       1.00      0.99      1.00      1335
                           Солодощі       0.90      0.96      0.93      2106
                    Соуси та спеції       0.87      0.92      0.89       675
                    Тютюнові вироби       0.99      0.99      0.99       362
                    Фрукти та овочі       0.82      0.82      0.82       949

                           accuracy                           0.94     19629
                          macro avg       0.93      0.94      0.93     19629
                       weighted avg       0.94      0.94      0.94     19629

Our results satisfy us, so we'll proceed to final stages.

# Final training

In [44]:
final_pipeline = Pipeline([
    ('tfidf', TfidfVectorizer(
        analyzer='char_wb', 
        ngram_range=(1, best_params['ngram_max'])
    )),
    ('classifier', MultinomialNB(alpha=best_params['alpha']))
])

In [45]:
final_pipeline.fit(df['preprocessed'], df['category'])

Pipeline(steps=[('tfidf',
                 TfidfVectorizer(analyzer='char_wb', ngram_range=(1, 5))),
                ('classifier', MultinomialNB(alpha=0.001217344949717882))])

# Exporting

In [48]:
joblib.dump(final_pipeline, MODEL_EXPORT_PATH)

['../app/models/exports/model.joblib']

In [52]:
with open(CATEGORIES_EXPORT_PATH, 'w', encoding='utf-8') as f:
    json.dump(categories_to_leave, f, ensure_ascii=False, indent=4)